#!/bin/bash

correct=1
correct_age=$(( ( RANDOM % 10 ) + 1 ))
while [ $correct -le 3 ]
 do
   echo "Guess the correct age! (1 - 100)"
   read guessed_age
     if (($guessed_age < 1 )); then
       echo "That is not in the valid age range"
     elif (($guessed_age > 100 )); then
       echo "That is not in the valid age range"
     elif (($guessed_age == $correct_age)); then
       echo "That is correct!"
       correct=$(( $correct + 3 ))            #If the answer is correct, make the loop stop immediately
     else
       echo "That is not correct!"
       correct=$(( $correct + 1 ))             #If the answer is incorrect, allow 3 guesses
       continue
     fi
done


